apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-new-year-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my1app
  template:
    metadata:
      labels:
        app: my1app
    spec:
      containers:
      - name: mymsgapp
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000
