apiVersion: v1
kind: Service
metadata:
  name: happy-new-year-service
spec:
  type: NodePort      # This makes the app accessible on your Ubuntu IP
  selector:
    app: my1app     # This MUST match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80        # The port the service will use internally
      targetPort: 5000 # The port your Flask app is actually running on
      nodePort: 32000 # The port you will type in your browser (range: 30000-32767)
